version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-cache-lint-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-cache-lint-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          name: scripts - Restore Yarn Package Cache
          keys:
            - yarn-packages-cache-lint-scripts-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/cache
      - run:
          name: scripts - Install Dependencies
          command: cd scripts && yarn install --frozen-lockfile --cache-folder ~/.cache/yarn-scripts
      - save_cache:
          name: scripts - Save Yarn Package Cache
          key: yarn-packages-cache-lint-scripts-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn-scripts
      - run:
          name: ESLint
          command: yarn lint
  unit:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-unit-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-unit-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Unit Test
          command: yarn test:unit:ci
      - store_test_results:
          path: unit-tests-results.xml
  e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.2-jammy
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-e2e-codex-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-e2e-codex-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: E2E Test
          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; yarn test:e2e --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  CI:
    jobs:
      - lint
      - unit
      - e2e
